/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mailuygulama;

import com.sun.xml.internal.org.jvnet.mimepull.MIMEMessage;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/**
 *
 * @author mehmet
 */
public class AnaPencere extends javax.swing.JFrame {
//Kullanım için gerekli, kullanıcıdan alınacak bilgiler.
    String SeninMailin;
    String GonderilecekMail;
    String Sifre;
    String Konu;
    String Mesaj;
    /**
     * Creates new form AnaPencere
     */
    public AnaPencere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        MesajGiris = new javax.swing.JEditorPane();
        GonderButon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SeninMailinGiris = new javax.swing.JTextField();
        GonderilecekMailGiris = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SifreGiris = new javax.swing.JTextField();
        KonuGiris = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(MesajGiris);

        GonderButon.setLabel("Gönder");
        GonderButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GonderButonActionPerformed(evt);
            }
        });

        jLabel1.setText("Mail Adresiniz :");

        jLabel2.setText("Gönderilecek Mail Adresi :");

        jLabel3.setText("Şifreniz :");

        jLabel4.setText("Konu :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(GonderButon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SeninMailinGiris)
                    .addComponent(GonderilecekMailGiris)
                    .addComponent(KonuGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(SifreGiris))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GonderButon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeninMailinGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(SifreGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GonderilecekMailGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KonuGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GonderButon.getAccessibleContext().setAccessibleName("MailBtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GonderButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GonderButonActionPerformed
    
        
     //Mail bilgilerimizin alınması.   
    SeninMailin=SeninMailinGiris.getText();
    GonderilecekMail=GonderilecekMailGiris.getText();
    Sifre=SifreGiris.getText();
    Konu=KonuGiris.getText();
    Mesaj=MesajGiris.getText();
        // SMTP ile gmail'imize bağlanmammız için gereken protokol bilgileri girilecek.
        Properties props= new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");//SMTP Host Bilgileri,
        props.put("mail.smtp.socketFactory.port",  "465");//SSl için SMTP Port Bilgileri,
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");//SSL Kullanımı,
        props.put("mail.smtp.auth", "true");//Kimlik Doğrulama aktif,
        props.put("mail.smt.port", "465");//SMTP Port Bilgileri,
        
        //Oturumumuzu açıyoruz.
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
        //Şifreyle doğrulama bilgileri.
        protected PasswordAuthentication getPasswordAuthentication(){
        
        return new PasswordAuthentication(SeninMailin,Sifre);
        }
                
        });          
        try {
            //Gönderilecek mailin içerik ve gereksinim bilgilerini giriyoruz.
            Message msg= new MimeMessage(session);
            msg.setFrom(new InternetAddress(SeninMailin));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(GonderilecekMail));
            msg.setSubject(Konu);
            msg.setText(Mesaj);
            Transport.send(msg);
            JOptionPane.showMessageDialog(null, "Mesaj gönderildi");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mesaj Gönderilemedi !!!"+e);
        }
    }//GEN-LAST:event_GonderButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaPencere().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GonderButon;
    private javax.swing.JTextField GonderilecekMailGiris;
    private javax.swing.JTextField KonuGiris;
    private javax.swing.JEditorPane MesajGiris;
    private javax.swing.JTextField SeninMailinGiris;
    private javax.swing.JTextField SifreGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
